package com.example.demo.utils;

public class Constant {
	
	public static String hour_mint[] = {
			" ",
		    "One",
		    "Two",
		    "Three",
		    "Four",
		    "Five",
		    "Six",
		    "Seven",
		    "Eight",
		    "Nine",
		    "Ten",
		    "Eleven",
		    "Twelve",
		    "Thirteen",
		    "Fourteen",
		    "Fifteen",
		    "Sixteen",
		    "Seventeen",
		    "Eighteen",
		    "Nineteen",
		    "Twenty",
		    "Twenty one",
		    "Twenty two",
		    "Twenty three",
		    "Twenty four",
		    "Twenty five",
		    "Twenty six",
		    "Twenty seven",
		    "Twenty eight",
		    "Twenty nine",
		    "Thirty",
		    "Thirty One",
		    "Thirty two",
		    "Thirty three",
		    "Thirty four",
		    "Thirty five",
		    "Thirty six",
		    "Thirty seven",
		    "Thirty eight",
		    "Thirty nine",
		    "Fourty",
		    "Fourty One",
		    "Fourty two",
		    "Fourty three",
		    "Fourty four",
		    "Fourty five",
		    "Fourty six",
		    "Fourty seven",
		    "Fourty eight",
		    "Fourty nine",
		    "Fifty",
		    "Fifty One",
		    "Fifty two",
		    "Fifty three",
		    "Fifty four",
		    "Fifty five",
		    "Fifty six",
		    "Fifty seven",
		    "Fifty eight",
		    "Fifty nine",
		    "Sixty",
		   };

}
